@echo off
setlocal enabledelayedexpansion
set mkvpropedit="C:\Program Files\MKVToolNix\mkvpropedit.exe"  


FOR %%A IN ("%CD%\*.mkv") do (
  set title=""
  set str=%%A
  set str=!str:~-6!
  set iString= !str:~0,2! 
  set /a i=!iString!

  IF !i! GEQ 1 ( IF  !i! LEQ 3 (set title="East Blue-Romance Dawn"))
  IF !i! GEQ 4 ( IF  !i! LEQ 8 (set title="East Blue-Orange Town"))
  IF !i! GEQ 9 ( IF  !i! LEQ 18 (set title="East Blue-Syrup Village"))
  IF !i! GEQ 19 ( IF  !i! LEQ 30 (set title="East Blue-Baratie"))
  IF !i! GEQ 31 ( IF  !i! LEQ 44 (set title="East Blue-Arlong park"))
  IF !i! EQU 45 (set title="East Blue-Loguetown")
  IF !i! GEQ 46 ( IF  !i! LEQ 47 (set title="East Blue-Buggy's Crew Adventure Chronicles"))
  IF !i! GEQ 48 ( IF  !i! LEQ 53 (set title="East Blue-Logetown"))
  IF !i! GEQ 54 ( IF  !i! LEQ 61 (set title="East Blue-Warship Island"))
  IF !i! GEQ 62 ( IF  !i! LEQ 63 (set title="Arabasta-Reverse Mountain"))
  IF !i! GEQ 64 ( IF  !i! LEQ 67 (set title="Arabasta-Whisky Peak"))
  IF !i! GEQ 68 ( IF  !i! LEQ 69 (set title="Arabasta-Diary of Koby-Meppo"))
  IF !i! GEQ 70 ( IF  !i! LEQ 77 (set title="Arabasta-Little Garden"))
  IF !i! GEQ 78 ( IF  !i! LEQ 91 (set title="Arabasta-Drum Island"))
  IF !i! GEQ 92 ( IF  !i! LEQ 130 (set title="Arabasta"))
  IF !i! GEQ 131 ( IF  !i! LEQ 135 (set title="Arabasta-Filler arc-Post-Arabasta"))
  IF !i! GEQ 136 ( IF  !i! LEQ 138 (set title="Sky Island-Filler arc-Goat Island"))
  IF !i! GEQ 139 ( IF  !i! LEQ 143 (set title="Sky Island-Filler arc-Ruluka Island"))
  IF !i! GEQ 144 ( IF  !i! LEQ 152 (set title="Sky Island-Jaya"))
  IF !i! GEQ 153 ( IF  !i! LEQ 195 (set title="Sky Island-Skypiea"))
  IF !i! GEQ 196 ( IF  !i! LEQ 206 (set title="Sky Island-Filler arc-G-8"))
  IF !i! GEQ 207 ( IF  !i! LEQ 219 (set title="Water 7-Long Ring Long Land"))
  IF !i! GEQ 220 ( IF  !i! LEQ 224 (set title="Water 7-Ocean's Dream"))
  IF !i! GEQ 225 ( IF  !i! LEQ 228 (set title="Water 7-Filler arc-Foxy's Return"))
  IF !i! GEQ 229 ( IF  !i! LEQ 263 (set title="Water 7"))
  IF !i! GEQ 264 ( IF  !i! LEQ 290 (set title="Water 7-Enies Lobby"))
  IF !i! GEQ 291 ( IF  !i! LEQ 292 (set title="Water 7-Special Episode Boss Luffy Historical Special"))
  IF !i! GEQ 293 ( IF  !i! LEQ 302 (set title="Water 7-Enies Lobby"))
  IF !i! EQU 303  (set title="Water 7-Special Episode Boss Luffy Historical Special")
  IF !i! GEQ 304 ( IF  !i! LEQ 312 (set title="Water 7-Enies Lobby"))
  IF !i! GEQ 313 ( IF  !i! LEQ 325 (set title="Water 7-Post-Enies Lobby"))
  IF !i! GEQ 326 ( IF  !i! LEQ 335 (set title="Thriller Bark-Ice Hunter"))
  IF !i! EQU 336 (set title="Thriller Bark-Special Episode-Chopper Man Special")
  IF !i! GEQ 337 ( IF  !i! LEQ 381 (set title="Thriller Bark-Thriller Bark"))
  IF !i! GEQ 382 ( IF  !i! LEQ 384 (set title="Thriller Bark-Filler arc-Spa Island"))
  IF !i! GEQ 385 ( IF  !i! LEQ 405 (set title="Summit War-Sabaody Archipelago"))
  IF !i! GEQ 406 ( IF  !i! LEQ 407 (set title="Summit War-Special Episode Boss Luffy Historical Special"))
  IF !i! GEQ 408 ( IF  !i! LEQ 417 (set title="Summit War-Amazon Lily"))
  IF !i! GEQ 418 ( IF  !i! LEQ 421 (set title="Summit War-Straw Hat's Seperation Serial"))
  IF !i! GEQ 422 ( IF  !i! LEQ 425 (set title="Summit War-Impel Down"))
  IF !i! GEQ 426 ( IF  !i! LEQ 429 (set title="Summit War-Foller arc-Little East Blue"))
  IF !i! GEQ 430 ( IF  !i! LEQ 452 (set title="Summit War-Impel Down"))
  IF !i! GEQ 453 ( IF  !i! LEQ 456 (set title="Summit War-Straw Hat's Seperation Serial"))
  IF !i! GEQ 457 ( IF  !i! LEQ 489 (set title="Summit War-Marineford"))
  IF !i! GEQ 490 ( IF  !i! LEQ 491 (set title="Summit War-Post-War"))
  IF !i! EQU 492 (set title="Summit War-Special Episode Toriko Crossover")
  IF !i! GEQ 493 ( IF  !i! LEQ 516 (set title="Summit War-Post-War"))
  IF !i! GEQ 517 ( IF  !i! LEQ 522 (set title="Fish-Man Island-Return to Sabaody"))
  IF !i! GEQ 523 ( IF  !i! LEQ 574 (set title="Fish-Man Island"))
  IF !i! GEQ 575 ( IF  !i! LEQ 578 (set title="Dressrosa-Filler arc-Z's Ambition"))
  IF !i! GEQ 579 ( IF  !i! LEQ 589 (set title="Dressrosa-Punk Hazard"))
  IF !i! EQU 590 (set title="Dressrosa-Special Episode Toriko & Dragon Ball Crossover")
  IF !i! GEQ 591 ( IF  !i! LEQ 625 (set title="Dressrosa-Punk Hazard"))
  IF !i! GEQ 625 ( IF  !i! LEQ 628 (set title="Dressrosa-Caeser Retrieval"))
  IF !i! GEQ 629 ( IF  !i! LEQ 746 (set title="Dressrosa"))
  IF !i! GEQ 747 ( IF  !i! LEQ 750 (set title="Four Emperors-Filler arc-Silver Mine"))
  IF !i! GEQ 751 ( IF  !i! LEQ 779 (set title="Four Emperors-Zou"))
  IF !i! GEQ 780 ( IF  !i! LEQ 782 (set title="Four Emperors-Filler arc-Marine Rookie"))
  IF !i! GEQ 783 ( IF  !i! LEQ 877 (set title="Four Emperors-Whole Cake Island"))
  IF !i! GEQ 878 ( IF  !i! LEQ 889 (set title="Four Emperors-Reverie"))
  IF !i! GEQ 890 ( IF  !i! LEQ 894 (set title="Four Emperors-Wano-Act I"))
  IF !i! GEQ 895 ( IF  !i! LEQ 896 (set title="Four Emperors-Filler arc-Cidre Guild"))
  IF !i! GEQ 897 ( IF  !i! LEQ 906 (set title="Four Emperors-Wano-Act I"))
  IF !i! EQU 907 (set title="Four Emperors-Special Episode-Anime 20th Anniversary Special")
  IF !i! GEQ 908 ( IF  !i! LEQ 916 (set title="Four Emperors-Wano-Act I"))
  IF !i! EQU 917 (set title="Four Emperors-Gecko Moria vs Blackbeard")
  IF !i! GEQ 918 ( IF  !i! LEQ 956 (set title="Four Emperors-Wano-Act II"))
  IF !i! GEQ 957 ( IF  !i! LEQ 958 (set title="Four Emperors-Big News From Reverie"))
  IF !i! GEQ 959 ( IF  !i! LEQ 1028 (set title="Four Emperors-Wano-Act III"))
  IF !i! GEQ 1029 ( IF  !i! LEQ 1030 (set title="Four Emperors-Filler arc-Uta's Past"))
  IF !i! GEQ 1031 (set title="Four Emperors-Wano-Act III")
  %mkvpropedit% "%CD%/%%~nA.mkv" --set "title=""!title!"
)
@pause
